### ISSUE TITLE
Error: Expecting a single string value: [type=character; extent=0].

### ISSUE THREAD

**Issue by smuyengwa79** [JanMarvin/RQDA#12] opened 2020-10-16 21:50 UTC
Error: Expecting a single string value: [type=character; extent=0].

This error occurs when I try  to specify the code categories to codes

locale:
[1] LC_COLLATE=English_Zimbabwe.1252  LC_CTYPE=English_Zimbabwe.1252   
[3] LC_MONETARY=English_Zimbabwe.1252 LC_NUMERIC=C                     
[5] LC_TIME=English_Zimbabwe.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] wordcloud_2.6        RColorBrewer_1.1-2   bbplot_0.2          
 [4] gtsummary_1.3.5      table1_1.2           readxl_1.3.1        
 [7] forcats_0.5.0        stringr_1.4.0        dplyr_1.0.2         
[10] purrr_0.3.4          readr_1.4.0          tidyr_1.1.2         
[13] tibble_3.0.3         ggplot2_3.3.2        tidyverse_1.3.0     
[16] RQDA_0.3-2           stringi_1.5.3        DBI_1.1.0           
[19] gWidgets2RGtk2_1.0-7 gWidgets2_1.0-8      digest_0.6.25       
[22] RGtk2_2.20.36        memoise_1.1.0        RSQLite_2.2.1       

loaded via a namespace (and not attached):
 [1] httr_1.4.2        bit64_4.0.5       jsonlite_1.7.1    modelr_0.1.8     
 [5] Formula_1.2-3     assertthat_0.2.1  blob_1.2.1        cellranger_1.1.0 
 [9] slam_0.1-47       yaml_2.2.1        gdtools_0.2.2     pillar_1.4.6     
[13] backports_1.1.10  glue_1.4.2        uuid_0.1-4        rvest_0.3.6      
[17] colorspace_1.4-1  htmltools_0.5.0   tm_0.7-7          pkgconfig_2.0.3  
[21] broom_0.7.1       haven_2.3.1       bookdown_0.20     scales_1.1.1     
[25] officer_0.3.14    generics_0.0.2    ellipsis_0.3.1    withr_2.3.0      
[29] NLP_0.2-1         cli_2.0.2         magrittr_1.5      crayon_1.3.4     
[33] evaluate_0.14     fs_1.5.0          fansi_0.4.1       xml2_1.3.2       
[37] tools_4.0.2       data.table_1.13.0 hms_0.5.3         lifecycle_0.2.0  
[41] flextable_0.5.11  munsell_0.5.0     reprex_0.3.0      zip_2.1.1        
[45] compiler_4.0.2    systemfonts_0.3.2 rlang_0.4.8       grid_4.0.2       
[49] rstudioapi_0.11   igraph_1.2.6      base64enc_0.1-3   rmarkdown_2.4    
[53] gtable_0.3.0      R6_2.4.1          lubridate_1.7.9   knitr_1.30       
[57] bit_4.0.4         utf8_1.1.4        parallel_4.0.2    Rcpp_1.0.5       
[61] vctrs_0.3.4       dbplyr_1.4.4      tidyselect_1.1.0  xfun_0.18

**Comment by JanMarvin** [comment] 2020-10-16 23:08
I'll look into it. Looks like RQDA is not passing to Rgtk2 what's supposed to be passed. Could you please add a few more hints how to reproduce the error; e.g., what do I have to do to reproduce it? Sorry if this sounds stupid, but as stated before, I'm not and never have been using RQDA myself. Every little hint can help me identify and solve the issue 😊

**Comment by JanMarvin** [comment] 2020-10-16 23:18
probably completely harmless, might be a change how Rgtk and Rgtk2 treat missing values, for instance when closing the file open dialogue without having a file selected

**Comment by JanMarvin** [comment] 2020-10-17 08:41
Ah got it. You have to select a code category first. Let me see if I can add some kind of dialog for this

**Comment by JanMarvin** [comment] 2020-10-17 09:42
I've added guards for this in https://github.com/JanMarvin/RQDA/commit/7fbc4f594b3542f047f29de1648da358b7c9b1fe see e.g. https://github.com/JanMarvin/RQDA/blob/master/R/CodeCatButton.R#L158-L163

I have not fixed all of the many possible cases where RQDA might loose scope (e.g., after deletion of a code category you can not click delete again immediately). If you want more safeguards pull requests are welcome!

**Closed by JanMarvin** 2020-10-17 09:42 UTC
